/*
 * File: app/store/Tweets.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoTweet.store.Tweets', {
    extend: 'Ext.data.Store',
    alias: 'store.tweets',
    requires: [
        'GeoTweet.model.Tweet'
    ],

    config: {
        autoLoad: false,
        model: 'GeoTweet.model.Tweet',
        storeId: 'Tweets',
        proxy: {
            type: 'jsonp',
            extraParams: {
                rpp: 100,
                geocode: '40.714186,-74.006414,500mi',
                q: 'google',
                uniqueify: Math.random()
            },
            url: 'http://search.twitter.com/search.json',
            reader: {
                type: 'json',
                rootProperty: 'results'
            }
        }
    }
});