/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoTweet.view.Viewport', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.viewport',
    requires: [
        'GeoTweet.view.Map',
        'GeoTweet.view.Timeline'
    ],

    config: {
        tabBar: {
            docked: 'bottom',
            ui: 'light'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                ui: 'neutral',
                title: 'GeoTweetss',
                layout: {
                    pack: 'end',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'buttonRefresh',
                        iconCls: 'refresh',
                        iconMask: true
                    }
                ]
            },
            {
                xtype: 'map',
                title: 'Map',
                iconCls: 'locate'
            },
            {
                xtype: 'timeline',
                title: 'Timeline',
                iconCls: 'home'
            }
        ]
    }

});