/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('GeoTweet.controller.Main', {
    extend: 'Ext.app.Controller',
    alias: 'controller.main',
    config: {
        refs: {
            timeline: 'timeline',
            map: 'map'
        },

        control: {
            "viewport #buttonRefresh": {
                tap: 'onButtonTap'
            }
        }
    },

    onButtonTap: function(button, e, options) {


        var store = this.getTimeline().getStore(), 
        coords = this.getMap()._geo.config,
        geocode = '40.714186,-74.006414,' + '500mi';
        store.getProxy().setExtraParam('geocode', geocode);
        store.load({
            scope: this,
            callback: function(records) {
                this.getMap().processTweets(records);
            }
        });


    }

});